name = "all-ai"
compatibility_date = "2024-04-04"
main = "src/index.ts"
node_compat = true

kv_namespaces = [
  { binding = "KVDATA", id = "xxxxxxxxxxxxxxxxx" }
]

[vars]
ENVIRONMENT = 'dev'
CUSTOM_HEADERS_TO_IGNORE = []

#
#Configuration for DEVELOPMENT environment
#
[env.staging]
name = "all-ai-dev"

[env.staging.vars]
ENVIRONMENT = 'staging'
CUSTOM_HEADERS_TO_IGNORE = []

[[d1_databases]]
binding = "D1DATA"
database_name = "portkey_ai"
database_id = "xxxxxxxxxxxx"


#
#Configuration for PRODUCTION environment
#
[env.production]
name = "all-ai"
logpush=true

[env.production.vars]
ENVIRONMENT = 'production'
CUSTOM_HEADERS_TO_IGNORE = []
